/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardPage: typeof import('./src/components/BoardPage.vue')['default']
    BoardTest: typeof import('./src/components/BoardTest.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LoginCallbackPage: typeof import('./src/components/LoginCallbackPage.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    PlayPage: typeof import('./src/components/PlayPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
